steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/sampsonjoliver/retro']
    dir: './functions'
  - name: gcr.io/cloud-builders/yarn
    args: ['install']
    dir: './functions'
  - name: gcr.io/cloud-builders/yarn
    args: ['build']
    dir: './functions'
  - name: gcr.io/cloud-builders/yarn
    entrypoint: 'yarn'
    args: ['deploy']
    secretEnv: ['FIREBASE_TOKEN']
  - name: gcr.io/cloud-builders/yarn
    args: ['deploy:firestore']
    secretEnv: ['FIREBASE_TOKEN']
    dir: './functions'

secrets:
  - kmsKeyName: projects/retro-e4947/locations/global/keyRings/retro-kms/cryptoKeys/prod
    secretEnv:
      FIREBASE_TOKEN: CiQA3e0LJJ37X3TEMbQ3rQ6ZeYji6ppec1jPEYPcz3imfjMtNTwSVgCf1+vCg0OCV0ODd/htt4nv64IQ2InmPzCm8wTkPT9SYxPEmMfz9gjFSkdI0gMdIzaapfjI1NZBjFOgTVS//95BRQ3BmIu6MrBG/sIQWPEdU3V5LW3w
