steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/sampsonjoliver/retro']
  - name: gcr.io/cloud-builders/yarn
    args: ['install']
    dir: './${_DIR}'
  - name: gcr.io/cloud-builders/yarn
    args: ['build']
    dir: './${_DIR}'
  - name: gcr.io/cloud-builders/yarn
    entrypoint: 'yarn'
    args: ['deploy --token ${_DEPLOY_TOKEN}']
    dir: './${_DIR}'
