steps:
  - name: gcr.io/cloud-builders/yarn
    id: installApp
    waitFor: ['-']
    args: ['install']
    dir: './apps'
  - name: gcr.io/cloud-builders/yarn
    waitFor: 
    - installApp
    args: ['test']
    dir: './functions'

  - name: gcr.io/cloud-builders/yarn
    id: installFuncs
    waitFor: ['-']
    args: ['install']
    dir: './functions'
  - name: gcr.io/cloud-builders/yarn
    waitFor: 
    - installFuncs
    args: ['test']
    dir: './functions'

timeout: 600s